image: openjdk:8-jdk

stages:
  - build
  - test

build_rcs_cis:
  stage: build
  tags:
    - docker
  artifacts:
    when: always
    expire_in: 1 week
    name: "rcs-sdk-${CI_BUILD_REF}"
    paths:
      - build/
  script:
    - ./gradlew clean build sonarqube -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME -Dsonar.gitlab.project_id=$CI_PROJECT_PATH -Dsonar.analysis.mode=preview -Dsonar.gitlab.json_mode=CODECLIMATE -Pcoverage
